package ztw

import (
	"fmt"
	"strings"

	"github.com/fabiotavarespr/iso3166"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

// Validate Location Management Options
var supportedLocationManagementCountries = []string{
	"NONE", "AFGHANISTAN", "ALAND_ISLANDS", "ALBANIA", "ALGERIA", "AMERICAN_SAMOA", "ANDORRA", "ANGOLA", "ANGUILLA", "ANTARCTICA", "ANTIGUA_AND_BARBUDA", "ARGENTINA", "ARMENIA", "ARUBA", "AUSTRALIA", "AUSTRIA", "AZERBAIJAN", "BAHAMAS", "BAHRAIN", "BANGLADESH", "BARBADOS", "BELARUS", "BELGIUM", "BELIZE", "BENIN", "BERMUDA", "BHUTAN", "BOLIVIA", "BOSNIA_AND_HERZEGOVINA", "BOTSWANA", "BRAZIL", "BRITISH_INDIAN_OCEAN_TERRITORY", "BRUNEI_DARUSSALAM", "BULGARIA", "BURKINA_FASO", "BURUNDI", "CAMBODIA", "CAMEROON", "CANADA", "CAPE_VERDE", "CAYMAN_ISLANDS", "CENTRAL_AFRICAN_REPUBLIC", "CHAD", "CHILE", "CHINA", "CHRISTMAS_ISLAND", "COCOS_KEELING_ISLANDS", "COLOMBIA", "COMOROS", "DEMOCRATIC_REPUBLIC_OF_CONGO_CONGO_KINSHASA", "CONGO_CONGO_BRAZZAVILLE", "COOK_ISLANDS", "COSTA_RICA", "COTE_DIVOIRE", "CROATIA", "CUBA", "CYPRUS", "CZECH_REPUBLIC", "DENMARK", "DJIBOUTI", "DOMINICAN_REPUBLIC", "DOMINICA", "ECUADOR", "EGYPT", "EL_SALVADOR", "EQUATORIAL_GUINEA", "ERITREA", "ESTONIA", "ETHIOPIA", "FALKLAND_ISLANDS", "FAROE_ISLANDS", "FIJI", "FINLAND", "FRANCE", "FRENCH_GUIANA", "FRENCH_POLYNESIA", "FRENCH_SOUTHERN_TERRITORIES", "GABON", "GAMBIA", "GEORGIA", "GERMANY", "GHANA", "GIBRALTAR", "GREECE", "GREENLAND", "GRENADA", "GUADELOUPE", "GUAM", "GUATEMALA", "GUERNSEY", "GUINEA_BISSAU", "GUINEA", "GUYANA", "HAITI", "HONDURAS", "HONG_KONG", "HUNGARY", "ICELAND", "INDIA", "INDONESIA", "IRAN", "IRAQ", "IRELAND", "ISLE_OF_MAN", "ISRAEL", "ITALY", "JAMAICA", "JAPAN", "JERSEY", "JORDAN", "KAZAKHSTAN", "KENYA", "KIRIBATI", "KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF", "KOREA_REPUBLIC_OF", "KUWAIT", "KYRGYZSTAN", "LAO_PEOPLES_DEMOCRATIC_REPUBLIC", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYAN_ARAB_JAMAHIRIYA", "LIECHTENSTEIN", "LITHUANIA", "LUXEMBOURG", "MACAO", "MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES", "MALI", "MALTA", "MARSHALL_ISLANDS", "MARTINIQUE", "MAURITANIA", "MAURITIUS", "MAYOTTE", "MEXICO", "MICRONESIA_FEDERATED_STATES_OF", "MOLDOVA", "MONACO", "MONGOLIA", "MONTENEGRO", "MONTSERRAT", "MOROCCO", "MOZAMBIQUE", "MYANMAR", "NAMIBIA", "NAURU", "NEPAL", "NETHERLANDS_ANTILLES", "NETHERLANDS", "NEW_CALEDONIA", "NEW_ZEALAND", "NICARAGUA", "NIGERIA", "NIGER", "NIUE", "NORFOLK_ISLAND", "NORTHERN_MARIANA_ISLANDS", "NORWAY", "OCCUPIED_PALESTINIAN_TERRITORY", "OMAN", "PAKISTAN", "PALAU", "PANAMA", "PAPUA_NEW_GUINEA", "PARAGUAY", "PERU", "PHILIPPINES", "PITCAIRN", "POLAND", "PORTUGAL", "PUERTO_RICO", "QATAR", "REUNION", "ROMANIA", "RUSSIAN_FEDERATION", "RWANDA", "SAINT_BARTHELEMY", "SAINT_KITTS_AND_NEVIS", "SAINT_LUCIA", "SAINT_MARTIN_FRENCH_PART", "SAINT_VINCENT_AND_THE_GRENADINES", "SAMOA", "SAN_MARINO", "SAO_TOME_AND_PRINCIPE", "SAUDI_ARABIA", "SENEGAL", "SERBIA", "SEYCHELLES", "SIERRA_LEONE", "SINGAPORE", "SLOVAKIA", "SLOVENIA", "SOLOMON_ISLANDS", "SOMALIA", "SOUTH_AFRICA", "SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS", "SPAIN", "SRI_LANKA", "ST_HELENA", "ST_PIERRE_AND_MIQUELON", "SUDAN", "SURINAME", "SVALBARD_AND_JAN_MAYEN_ISLANDS", "SWAZILAND", "SWEDEN", "SWITZERLAND", "SYRIAN_ARAB_REPUBLIC", "TAIWAN", "TAJIKISTAN", "TANZANIA", "THAILAND", "TIMOR_LESTE", "TOGO", "TOKELAU", "TONGA", "TRINIDAD_AND_TOBAGO", "TUNISIA", "TURKEY", "TURKMENISTAN", "TURKS_AND_CAICOS_ISLANDS", "TUVALU", "UGANDA", "UKRAINE", "UNITED_ARAB_EMIRATES", "UNITED_KINGDOM", "UNITED_STATES_MINOR_OUTLYING_ISLANDS", "UNITED_STATES", "URUGUAY", "UZBEKISTAN", "VANUATU", "VATICAN_CITY_STATE", "VENEZUELA", "VIET_NAM", "VIRGIN_ISLANDS_BRITISH", "VIRGIN_ISLANDS_US", "WALLIS_AND_FUTUNA_ISLANDS", "WESTERN_SAHARA", "YEMEN", "ZAMBIA", "ZIMBABWE",
}

func validateLocationManagementCountries() schema.SchemaValidateFunc {
	return validation.StringInSlice(supportedLocationManagementCountries, false)
}

var supportedLocationManagemeTimeZones = []string{
	"NOT_SPECIFIED", "GMT_12_00_DATELINE", "GMT_11_00_SAMOA", "GMT_10_00_US_HAWAIIAN_TIME", "GMT_09_30_MARQUESAS", "GMT_09_00_US_ALASKA_TIME", "GMT_08_30_PITCARN", "GMT_08_00_PACIFIC_TIME", "GMT_07_00_US_MOUNTAIN_TIME", "GMT_07_00_US_MOUNTAIN_TIME_ARIZONA", "GMT_06_00_US_CENTRAL_TIME", "GMT_06_00_MEXICO", "GMT_05_00_US_EASTERN_TIME", "GMT_05_00_US_EASTERN_TIME_INDIANA", "GMT_05_00_COLUMBIA_PERU_SOUTH_AMERICA", "GMT_04_00_ATLANTIC_TIME", "GMT_03_30_NEWFOUNDLAND_CANADA", "GMT_03_00_ARGENTINA", "GMT_03_00_BRAZIL", "GMT_02_00_MID_ATLANTIC", "GMT_01_00_AZORES", "GMT", "GMT_01_00_WESTERN_EUROPE_GMT_01_00", "GMT_02_00_EASTERN_EUROPE_GMT_02_00", "GMT_02_00_EGYPT_GMT_02_00", "GMT_02_00_ISRAEL_GMT_02_00", "GMT_03_00_RUSSIA_GMT_03_00", "GMT_03_00_SAUDI_ARABIA_GMT_03_00", "GMT_03_30_IRAN_GMT_03_30", "GMT_04_00_ARABIAN_GMT_04_00", "GMT_04_30_AFGHANISTAN_GMT_04_30", "GMT_05_00_PAKISTAN_WEST_ASIA_GMT_05_00", "GMT_05_30_INDIA_GMT_05_30", "GMT_06_00_BANGLADESH_CENTRAL_ASIA_GMT_06_00", "GMT_06_30_BURMA_GMT_06_30", "GMT_07_00_BANGKOK_HANOI_JAKARTA_GMT_07_00", "GMT_08_00_CHINA_TAIWAN_GMT_08_00", "GMT_08_00_SINGAPORE_GMT_08_00", "GMT_08_00_AUSTRALIA_WT_GMT_08_00", "GMT_09_00_JAPAN_GMT_09_00", "GMT_09_00_KOREA_GMT_09_00", "GMT_09_30_AUSTRALIA_CT_GMT_09_30", "GMT_10_00_AUSTRALIA_ET_GMT_10_00", "GMT_10_30_AUSTRALIA_LORD_HOWE_GMT_10_30", "GMT_11_00_CENTRAL_PACIFIC_GMT_11_00", "GMT_11_30_NORFOLK_ISLANDS_GMT_11_30", "GMT_12_00_FIJI_NEW_ZEALAND_GMT_12_00", "AFGHANISTAN_ASIA_KABUL", "ALAND_ISLANDS_EUROPE_MARIEHAMN", "ALBANIA_EUROPE_TIRANE", "ALGERIA_AFRICA_ALGIERS", "AMERICAN_SAMOA_PACIFIC_PAGO_PAGO", "ANDORRA_EUROPE_ANDORRA", "ANGOLA_AFRICA_LUANDA", "ANGUILLA_AMERICA_ANGUILLA", "ANTARCTICA_CASEY", "ANTARCTICA_DAVIS", "ANTARCTICA_DUMONTDURVILLE", "ANTARCTICA_MAWSON", "ANTARCTICA_MCMURDO", "ANTARCTICA_PALMER", "ANTARCTICA_ROTHERA", "ANTARCTICA_SOUTH_POLE", "ANTARCTICA_SYOWA", "ANTARCTICA_VOSTOK", "ANTIGUA_AND_BARBUDA_AMERICA_ANTIGUA", "ARGENTINA_AMERICA_ARGENTINA_BUENOS_AIRES", "ARGENTINA_AMERICA_ARGENTINA_CATAMARCA", "ARGENTINA_AMERICA_ARGENTINA_CORDOBA", "ARGENTINA_AMERICA_ARGENTINA_JUJUY", "ARGENTINA_AMERICA_ARGENTINA_LA_RIOJA", "ARGENTINA_AMERICA_ARGENTINA_MENDOZA", "ARGENTINA_AMERICA_ARGENTINA_RIO_GALLEGOS", "ARGENTINA_AMERICA_ARGENTINA_SAN_JUAN", "ARGENTINA_AMERICA_ARGENTINA_TUCUMAN", "ARGENTINA_AMERICA_ARGENTINA_USHUAIA", "ARMENIA_ASIA_YEREVAN", "ARUBA_AMERICA_ARUBA", "AUSTRALIA_ADELAIDE", "AUSTRALIA_BRISBANE", "AUSTRALIA_BROKEN_HILL", "AUSTRALIA_CURRIE", "AUSTRALIA_DARWIN", "AUSTRALIA_EUCLA", "AUSTRALIA_HOBART", "AUSTRALIA_LINDEMAN", "AUSTRALIA_LORD_HOWE", "AUSTRALIA_MELBOURNE", "AUSTRALIA_PERTH", "AUSTRALIA_SYDNEY", "AUSTRIA_EUROPE_VIENNA", "AZERBAIJAN_ASIA_BAKU", "BAHAMAS_AMERICA_NASSAU", "BAHRAIN_ASIA_BAHRAIN", "BANGLADESH_ASIA_DHAKA", "BARBADOS_AMERICA_BARBADOS", "BELARUS_EUROPE_MINSK", "BELGIUM_EUROPE_BRUSSELS", "BELIZE_AMERICA_BELIZE", "BENIN_AFRICA_PORTO_NOVO", "BERMUDA_ATLANTIC_BERMUDA", "BHUTAN_ASIA_THIMPHU", "BOLIVIA_AMERICA_LA_PAZ", "BOSNIA_AND_HERZEGOVINA_EUROPE_SARAJEVO", "BOTSWANA_AFRICA_GABORONE", "BRAZIL_AMERICA_ARAGUAINA", "BRAZIL_AMERICA_BAHIA", "BRAZIL_AMERICA_BELEM", "BRAZIL_AMERICA_BOA_VISTA", "BRAZIL_AMERICA_CAMPO_GRANDE", "BRAZIL_AMERICA_CUIABA", "BRAZIL_AMERICA_EIRUNEPE", "BRAZIL_AMERICA_FORTALEZA", "BRAZIL_AMERICA_MACEIO", "BRAZIL_AMERICA_MANAUS", "BRAZIL_AMERICA_NORONHA", "BRAZIL_AMERICA_PORTO_VELHO", "BRAZIL_AMERICA_RECIFE", "BRAZIL_AMERICA_RIO_BRANCO", "BRAZIL_AMERICA_SAO_PAULO", "BRITISH_INDIAN_OCEAN_TERRITORY_INDIAN_CHAGOS", "BRUNEI_DARUSSALAM_ASIA_BRUNEI", "BULGARIA_EUROPE_SOFIA", "BURKINA_FASO_AFRICA_OUAGADOUGOU", "BURUNDI_AFRICA_BUJUMBURA", "CAMBODIA_ASIA_PHNOM_PENH", "CAMEROON_AFRICA_DOUALA", "CANADA_AMERICA_ATIKOKAN", "CANADA_AMERICA_BLANC_SABLON", "CANADA_AMERICA_CAMBRIDGE_BAY", "CANADA_AMERICA_DAWSON_CREEK", "CANADA_AMERICA_DAWSON", "CANADA_AMERICA_EDMONTON", "CANADA_AMERICA_GLACE_BAY", "CANADA_AMERICA_GOOSE_BAY", "CANADA_AMERICA_HALIFAX", "CANADA_AMERICA_INUVIK", "CANADA_AMERICA_IQALUIT", "CANADA_AMERICA_MONCTON", "CANADA_AMERICA_MONTREAL", "CANADA_AMERICA_NIPIGON", "CANADA_AMERICA_PANGNIRTUNG", "CANADA_AMERICA_RAINY_RIVER", "CANADA_AMERICA_RANKIN_INLET", "CANADA_AMERICA_REGINA", "CANADA_AMERICA_RESOLUTE", "CANADA_AMERICA_ST_JOHNS", "CANADA_AMERICA_SWIFT_CURRENT", "CANADA_AMERICA_THUNDER_BAY", "CANADA_AMERICA_TORONTO", "CANADA_AMERICA_VANCOUVER", "CANADA_AMERICA_WHITEHORSE", "CANADA_AMERICA_WINNIPEG", "CANADA_AMERICA_YELLOWKNIFE", "CAPE_VERDE_ATLANTIC_CAPE_VERDE", "CAYMAN_ISLANDS_AMERICA_CAYMAN", "CENTRAL_AFRICAN_REPUBLIC_AFRICA_BANGUI", "CHAD_AFRICA_NDJAMENA", "CHILE_AMERICA_SANTIAGO", "CHILE_PACIFIC_EASTER", "CHINA_ASIA_CHONGQING", "CHINA_ASIA_HARBIN", "CHINA_ASIA_KASHGAR", "CHINA_ASIA_SHANGHAI", "CHINA_ASIA_URUMQI", "CHRISTMAS_ISLAND_INDIAN_CHRISTMAS", "COCOS_KEELING_ISLANDS_INDIAN_COCOS", "COLOMBIA_AMERICA_BOGOTA", "COMOROS_INDIAN_COMORO", "DEMOCRATIC_REPUBLIC_OF_CONGO_CONGO_KINSHASA_AFRICA_KINSHASA", "DEMOCRATIC_REPUBLIC_OF_CONGO_CONGO_KINSHASA_AFRICA_LUBUMBASHI", "CONGO_CONGO_BRAZZAVILLE_AFRICA_BRAZZAVILLE", "COOK_ISLANDS_PACIFIC_RAROTONGA", "COSTA_RICA_AMERICA_COSTA_RICA", "COTE_DIVOIRE_AFRICA_ABIDJAN", "CROATIA_EUROPE_ZAGREB", "CUBA_AMERICA_HAVANA", "CYPRUS_ASIA_NICOSIA", "CZECH_REPUBLIC_EUROPE_PRAGUE", "DENMARK_EUROPE_COPENHAGEN", "DJIBOUTI_AFRICA_DJIBOUTI", "DOMINICAN_REPUBLIC_AMERICA_SANTO_DOMINGO", "DOMINICA_AMERICA_DOMINICA", "ECUADOR_AMERICA_GUAYAQUIL", "ECUADOR_PACIFIC_GALAPAGOS", "EGYPT_AFRICA_CAIRO", "EL_SALVADOR_AMERICA_EL_SALVADOR", "EQUATORIAL_GUINEA_AFRICA_MALABO", "ERITREA_AFRICA_ASMARA", "ESTONIA_EUROPE_TALLINN", "ETHIOPIA_AFRICA_ADDIS_ABABA", "FALKLAND_ISLANDS_ATLANTIC_STANLEY", "FAROE_ISLANDS_ATLANTIC_FAROE", "FIJI_PACIFIC_FIJI", "FINLAND_EUROPE_HELSINKI", "FRANCE_EUROPE_PARIS", "FRENCH_GUIANA_AMERICA_CAYENNE", "FRENCH_POLYNESIA_PACIFIC_GAMBIER", "FRENCH_POLYNESIA_PACIFIC_MARQUESAS", "FRENCH_POLYNESIA_PACIFIC_TAHITI", "FRENCH_SOUTHERN_TERRITORIES_INDIAN_KERGUELEN", "GABON_AFRICA_LIBREVILLE", "GAMBIA_AFRICA_BANJUL", "GEORGIA_ASIA_TBILISI", "GERMANY_EUROPE_BERLIN", "GHANA_AFRICA_ACCRA", "GIBRALTAR_EUROPE_GIBRALTAR", "GREECE_EUROPE_ATHENS", "GREENLAND_AMERICA_DANMARKSHAVN", "GREENLAND_AMERICA_GODTHAB", "GREENLAND_AMERICA_SCORESBYSUND", "GREENLAND_AMERICA_THULE", "GRENADA_AMERICA_GRENADA", "GUADELOUPE_AMERICA_GUADELOUPE", "GUAM_PACIFIC_GUAM", "GUATEMALA_AMERICA_GUATEMALA", "GUERNSEY_EUROPE_GUERNSEY", "GUINEA_BISSAU_AFRICA_BISSAU", "GUINEA_AFRICA_CONAKRY", "GUYANA_AMERICA_GUYANA", "HAITI_AMERICA_PORT_AU_PRINCE", "HONDURAS_AMERICA_TEGUCIGALPA", "HONG_KONG_ASIA_HONG_KONG", "HUNGARY_EUROPE_BUDAPEST", "ICELAND_ATLANTIC_REYKJAVIK", "INDIA_ASIA_KOLKATA", "INDONESIA_ASIA_JAKARTA", "INDONESIA_ASIA_JAYAPURA", "INDONESIA_ASIA_MAKASSAR", "INDONESIA_ASIA_PONTIANAK", "IRAN_ASIA_TEHRAN", "IRAQ_ASIA_BAGHDAD", "IRELAND_EUROPE_DUBLIN", "ISLE_OF_MAN_EUROPE_ISLE_OF_MAN", "ISRAEL_ASIA_JERUSALEM", "ITALY_EUROPE_ROME", "JAMAICA_AMERICA_JAMAICA", "JAPAN_ASIA_TOKYO", "JERSEY_EUROPE_JERSEY", "JORDAN_ASIA_AMMAN", "KAZAKHSTAN_ASIA_ALMATY", "KAZAKHSTAN_ASIA_AQTAU", "KAZAKHSTAN_ASIA_AQTOBE", "KAZAKHSTAN_ASIA_ORAL", "KAZAKHSTAN_ASIA_QYZYLORDA", "KENYA_AFRICA_NAIROBI", "KIRIBATI_PACIFIC_ENDERBURY", "KIRIBATI_PACIFIC_KIRITIMATI", "KIRIBATI_PACIFIC_TARAWA", "KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF_ASIA_PYONGYANG", "KOREA_REPUBLIC_OF_ASIA_SEOUL", "KUWAIT_ASIA_KUWAIT", "KYRGYZSTAN_ASIA_BISHKEK", "LAO_PEOPLES_DEMOCRATIC_REPUBLIC_ASIA_VIENTIANE", "LATVIA_EUROPE_RIGA", "LEBANON_ASIA_BEIRUT", "LESOTHO_AFRICA_MASERU", "LIBERIA_AFRICA_MONROVIA", "LIBYAN_ARAB_JAMAHIRIYA_AFRICA_TRIPOLI", "LIECHTENSTEIN_EUROPE_VADUZ", "LITHUANIA_EUROPE_VILNIUS", "LUXEMBOURG_EUROPE_LUXEMBOURG", "MACAO_ASIA_MACAU", "MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF_EUROPE_SKOPJE", "MADAGASCAR_INDIAN_ANTANANARIVO", "MALAWI_AFRICA_BLANTYRE", "MALAYSIA_ASIA_KUALA_LUMPUR", "MALAYSIA_ASIA_KUCHING", "MALDIVES_INDIAN_MALDIVES", "MALI_AFRICA_BAMAKO", "MALTA_EUROPE_MALTA", "MARSHALL_ISLANDS_PACIFIC_KWAJALEIN", "MARSHALL_ISLANDS_PACIFIC_MAJURO", "MARTINIQUE_AMERICA_MARTINIQUE", "MAURITANIA_AFRICA_NOUAKCHOTT", "MAURITIUS_INDIAN_MAURITIUS", "MAYOTTE_INDIAN_MAYOTTE", "MEXICO_AMERICA_CANCUN", "MEXICO_AMERICA_CHIHUAHUA", "MEXICO_AMERICA_HERMOSILLO", "MEXICO_AMERICA_MAZATLAN", "MEXICO_AMERICA_MERIDA", "MEXICO_AMERICA_MEXICO_CITY", "MEXICO_AMERICA_MONTERREY", "MEXICO_AMERICA_TIJUANA", "MICRONESIA_FEDERATED_STATES_OF_PACIFIC_KOSRAE", "MICRONESIA_FEDERATED_STATES_OF_PACIFIC_PONAPE", "MICRONESIA_FEDERATED_STATES_OF_PACIFIC_TRUK", "MOLDOVA_EUROPE_CHISINAU", "MONACO_EUROPE_MONACO", "MONGOLIA_ASIA_CHOIBALSAN", "MONGOLIA_ASIA_HOVD", "MONGOLIA_ASIA_ULAANBAATAR", "MONTENEGRO_EUROPE_PODGORICA", "MONTSERRAT_AMERICA_MONTSERRAT", "MOROCCO_AFRICA_CASABLANCA", "MOZAMBIQUE_AFRICA_MAPUTO", "MYANMAR_ASIA_RANGOON", "NAMIBIA_AFRICA_WINDHOEK", "NAURU_PACIFIC_NAURU", "NEPAL_ASIA_KATMANDU", "NETHERLANDS_ANTILLES_AMERICA_CURACAO", "NETHERLANDS_EUROPE_AMSTERDAM", "NEW_CALEDONIA_PACIFIC_NOUMEA", "NEW_ZEALAND_PACIFIC_AUCKLAND", "NEW_ZEALAND_PACIFIC_CHATHAM", "NICARAGUA_AMERICA_MANAGUA", "NIGERIA_AFRICA_LAGOS", "NIGER_AFRICA_NIAMEY", "NIUE_PACIFIC_NIUE", "NORFOLK_ISLAND_PACIFIC_NORFOLK", "NORTHERN_MARIANA_ISLANDS_PACIFIC_SAIPAN", "NORWAY_EUROPE_OSLO", "OCCUPIED_PALESTINIAN_TERRITORY_ASIA_GAZA", "OMAN_ASIA_MUSCAT", "PAKISTAN_ASIA_KARACHI", "PALAU_PACIFIC_PALAU", "PANAMA_AMERICA_PANAMA", "PAPUA_NEW_GUINEA_PACIFIC_PORT_MORESBY", "PARAGUAY_AMERICA_ASUNCION", "PERU_AMERICA_LIMA", "PHILIPPINES_ASIA_MANILA", "PITCAIRN_PACIFIC_PITCAIRN", "POLAND_EUROPE_WARSAW", "PORTUGAL_ATLANTIC_AZORES", "PORTUGAL_ATLANTIC_MADEIRA", "PORTUGAL_EUROPE_LISBON", "PUERTO_RICO_AMERICA_PUERTO_RICO", "QATAR_ASIA_QATAR", "REUNION_INDIAN_REUNION", "ROMANIA_EUROPE_BUCHAREST", "RUSSIAN_FEDERATION_ASIA_ANADYR", "RUSSIAN_FEDERATION_ASIA_IRKUTSK", "RUSSIAN_FEDERATION_ASIA_KAMCHATKA", "RUSSIAN_FEDERATION_ASIA_KRASNOYARSK", "RUSSIAN_FEDERATION_ASIA_MAGADAN", "RUSSIAN_FEDERATION_ASIA_NOVOSIBIRSK", "RUSSIAN_FEDERATION_ASIA_OMSK", "RUSSIAN_FEDERATION_ASIA_SAKHALIN", "RUSSIAN_FEDERATION_ASIA_VLADIVOSTOK", "RUSSIAN_FEDERATION_ASIA_YAKUTSK", "RUSSIAN_FEDERATION_ASIA_YEKATERINBURG", "RUSSIAN_FEDERATION_EUROPE_KALININGRAD", "RUSSIAN_FEDERATION_EUROPE_MOSCOW", "RUSSIAN_FEDERATION_EUROPE_SAMARA", "RUSSIAN_FEDERATION_EUROPE_VOLGOGRAD", "RWANDA_AFRICA_KIGALI", "SAINT_BARTHELEMY_AMERICA_ST_BARTHELEMY", "SAINT_KITTS_AND_NEVIS_AMERICA_ST_KITTS", "SAINT_LUCIA_AMERICA_ST_LUCIA", "SAINT_MARTIN_FRENCH_PART_AMERICA_MARIGOT", "SAINT_VINCENT_AND_THE_GRENADINES_AMERICA_ST_VINCENT", "SAMOA_PACIFIC_APIA", "SAN_MARINO_EUROPE_SAN_MARINO", "SAO_TOME_AND_PRINCIPE_AFRICA_SAO_TOME", "SAUDI_ARABIA_ASIA_RIYADH", "SENEGAL_AFRICA_DAKAR", "SERBIA_EUROPE_BELGRADE", "SEYCHELLES_INDIAN_MAHE", "SIERRA_LEONE_AFRICA_FREETOWN", "SINGAPORE_ASIA_SINGAPORE", "SLOVAKIA_EUROPE_BRATISLAVA", "SLOVENIA_EUROPE_LJUBLJANA", "SOLOMON_ISLANDS_PACIFIC_GUADALCANAL", "SOMALIA_AFRICA_MOGADISHU", "SOUTH_AFRICA_AFRICA_JOHANNESBURG", "SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS_ATLANTIC_SOUTH_GEORGIA", "SPAIN_AFRICA_CEUTA", "SPAIN_ATLANTIC_CANARY", "SPAIN_EUROPE_MADRID", "SRI_LANKA_ASIA_COLOMBO", "ST_HELENA_ATLANTIC_ST_HELENA", "ST_PIERRE_AND_MIQUELON_AMERICA_MIQUELON", "SUDAN_AFRICA_KHARTOUM", "SURINAME_AMERICA_PARAMARIBO", "SVALBARD_AND_JAN_MAYEN_ISLANDS_ARCTIC_LONGYEARBYEN", "SWAZILAND_AFRICA_MBABANE", "SWEDEN_EUROPE_STOCKHOLM", "SWITZERLAND_EUROPE_ZURICH", "SYRIAN_ARAB_REPUBLIC_ASIA_DAMASCUS", "TAIWAN_ASIA_TAIPEI", "TAJIKISTAN_ASIA_DUSHANBE", "TANZANIA_AFRICA_DAR_ES_SALAAM", "THAILAND_ASIA_BANGKOK", "TIMOR_LESTE_ASIA_DILI", "TOGO_AFRICA_LOME", "TOKELAU_PACIFIC_FAKAOFO", "TONGA_PACIFIC_TONGATAPU", "TRINIDAD_AND_TOBAGO_AMERICA_PORT_OF_SPAIN", "TUNISIA_AFRICA_TUNIS", "TURKEY_EUROPE_ISTANBUL", "TURKMENISTAN_ASIA_ASHGABAT", "TURKS_AND_CAICOS_ISLANDS_AMERICA_GRAND_TURK", "TUVALU_PACIFIC_FUNAFUTI", "UGANDA_AFRICA_KAMPALA", "UKRAINE_EUROPE_KIEV", "UKRAINE_EUROPE_SIMFEROPOL", "UKRAINE_EUROPE_UZHGOROD", "UKRAINE_EUROPE_ZAPOROZHYE", "UNITED_ARAB_EMIRATES_ASIA_DUBAI", "UNITED_KINGDOM_EUROPE_LONDON", "UNITED_STATES_MINOR_OUTLYING_ISLANDS_PACIFIC_JOHNSTON", "UNITED_STATES_MINOR_OUTLYING_ISLANDS_PACIFIC_MIDWAY", "UNITED_STATES_MINOR_OUTLYING_ISLANDS_PACIFIC_WAKE", "UNITED_STATES_AMERICA_ADAK", "UNITED_STATES_AMERICA_ANCHORAGE", "UNITED_STATES_AMERICA_BOISE", "UNITED_STATES_AMERICA_CHICAGO", "UNITED_STATES_AMERICA_DENVER", "UNITED_STATES_AMERICA_DETROIT", "UNITED_STATES_AMERICA_INDIANA_INDIANAPOLIS", "UNITED_STATES_AMERICA_INDIANA_KNOX", "UNITED_STATES_AMERICA_INDIANA_MARENGO", "UNITED_STATES_AMERICA_INDIANA_PETERSBURG", "UNITED_STATES_AMERICA_INDIANA_TELL_CITY", "UNITED_STATES_AMERICA_INDIANA_VEVAY", "UNITED_STATES_AMERICA_INDIANA_VINCENNES", "UNITED_STATES_AMERICA_INDIANA_WINAMAC", "UNITED_STATES_AMERICA_JUNEAU", "UNITED_STATES_AMERICA_KENTUCKY_LOUISVILLE", "UNITED_STATES_AMERICA_KENTUCKY_MONTICELLO", "UNITED_STATES_AMERICA_LOS_ANGELES", "UNITED_STATES_AMERICA_MENOMINEE", "UNITED_STATES_AMERICA_NEW_YORK", "UNITED_STATES_AMERICA_NOME", "UNITED_STATES_AMERICA_NORTH_DAKOTA_CENTER", "UNITED_STATES_AMERICA_NORTH_DAKOTA_NEW_SALEM", "UNITED_STATES_AMERICA_PHOENIX", "UNITED_STATES_AMERICA_SHIPROCK", "UNITED_STATES_AMERICA_YAKUTAT", "UNITED_STATES_PACIFIC_HONOLULU", "URUGUAY_AMERICA_MONTEVIDEO", "UZBEKISTAN_ASIA_SAMARKAND", "UZBEKISTAN_ASIA_TASHKENT", "VANUATU_PACIFIC_EFATE", "VATICAN_CITY_STATE_EUROPE_VATICAN", "VENEZUELA_AMERICA_CARACAS", "VIET_NAM_ASIA_SAIGON", "VIRGIN_ISLANDS_BRITISH_AMERICA_TORTOLA", "VIRGIN_ISLANDS_US_AMERICA_ST_THOMAS", "WALLIS_AND_FUTUNA_ISLANDS_PACIFIC_WALLIS", "WESTERN_SAHARA_AFRICA_EL_AAIUN", "YEMEN_ASIA_ADEN", "ZAMBIA_AFRICA_LUSAKA", "ZIMBABWE_AFRICA_HARARE",
}

func validateLocationManagementTimeZones() schema.SchemaValidateFunc {
	return validation.StringInSlice(supportedLocationManagemeTimeZones, false)
}

func intAtMost(max int) schema.SchemaValidateDiagFunc {
	return func(i interface{}, k cty.Path) diag.Diagnostics {
		v, ok := i.(int)
		if !ok {
			return diag.Errorf("expected type of %s to be integer", k)
		}
		if v > max {
			return diag.Errorf("expected %s to be at most (%d), got %d", k, max, v)
		}
		return nil
	}
}

func intBetween(min, max int) schema.SchemaValidateDiagFunc {
	return func(i interface{}, k cty.Path) diag.Diagnostics {
		v, ok := i.(int)
		if !ok {
			return diag.Errorf("expected type of %s to be integer", k)
		}
		if v < min || v > max {
			return diag.Errorf("expected %s to be in the range (%d - %d), got %d", k, min, max, v)
		}
		return nil
	}
}

func stringIsMultiLine(i interface{}, k cty.Path) diag.Diagnostics {
	v, ok := i.(string)
	if !ok {
		return diag.Errorf("expected type of %s to be string", k)
	}
	if v == "" {
		return diag.Errorf("expected %q text to not be empty, got %v", k, i)
	}
	return nil
}

// Ensures consistent formatting for multi-line text (aligns properly)
func normalizeMultiLineString(val interface{}) string {
	str, ok := val.(string)
	if !ok || str == "" {
		return ""
	}

	// Trim leading/trailing whitespace for consistency
	str = strings.TrimSpace(str)

	// Ensure uniform indentation by trimming each line
	lines := strings.Split(str, "\n")
	for i := range lines {
		lines[i] = strings.TrimSpace(lines[i])
	}

	// Escape Terraform variable interpolation (`$` → `$$`)
	escapedStr := strings.Join(lines, "\n")
	escapedStr = strings.ReplaceAll(escapedStr, "$", "$$")

	// Ensure the final newline to match Terraform formatting
	return escapedStr + "\n"
}

// Suppresses differences in multi-line text by ignoring whitespace discrepancies
func noChangeInMultiLineText(k, oldText, newText string, d *schema.ResourceData) bool {
	if newText == "" {
		return true
	}

	// Normalize both values and compare
	oldTextNormalized := normalizeMultiLineString(oldText)
	newTextNormalized := normalizeMultiLineString(newText)

	return oldTextNormalized == newTextNormalized
}

func unescapeTerraformVariables(val string) string {
	// Convert `$$` back to `$` for the API
	return strings.ReplaceAll(val, "$$", "$")
}

// Validate Cloud Firewall Network Service Applications

func validateISOCountryCodes(value interface{}, key string) ([]string, []error) {
	var warnings []string
	var errors []error

	code, ok := value.(string)
	if !ok {
		errors = append(errors, fmt.Errorf("expected type of %s to be string", key))
		return warnings, errors
	}

	// Special values
	if code == "ANY" || code == "NONE" {
		return warnings, errors
	}

	// Check against ISO 3166 Alpha-2
	if !iso3166.ExistsIso3166ByAlpha2Code(code) {
		errors = append(errors, fmt.Errorf("'%s' is not a valid ISO-3166 Alpha-2 country code. Please visit the following site for reference: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes", code))
		return warnings, errors
	}

	return warnings, errors
}

var supportedCloudFirewallNwServicesTag = []string{
	"ICMP_ANY", "UDP_ANY", "TCP_ANY", "OTHER_NETWORK_SERVICE", "DNS", "NETBIOS", "FTP", "GNUTELLA", "H_323", "HTTP", "HTTPS", "IKE", "IMAP", "ILS", "IKE_NAT", "IRC", "LDAP", "QUIC", "TDS", "NETMEETING", "NFS", "NTP", "SIP", "SNMP", "SMB", "SMTP", "SSH", "SYSLOG", "TELNET", "TRACEROUTE", "POP3", "PPTP", "RADIUS", "REAL_MEDIA", "RTSP", "VNC", "WHOIS", "KERBEROS_SEC", "TACACS", "SNMPTRAP", "NMAP", "RSYNC", "L2TP", "HTTP_PROXY", "PC_ANYWHERE", "MSN", "ECHO", "AIM", "IDENT", "YMSG", "SCCP", "MGCP_UA", "MGCP_CA", "VDO_LIVE", "OPENVPN", "TFTP", "FTPS_IMPLICIT", "ZSCALER_PROXY_NW_SERVICES", "GRE_PROTOCOL", "ESP_PROTOCOL", "DHCP",
}

func validateCloudFirewallNwServicesTag() schema.SchemaValidateDiagFunc {
	return func(i interface{}, path cty.Path) diag.Diagnostics {
		value, ok := i.(string)
		if !ok {
			return diag.Diagnostics{
				{
					Severity: diag.Error,
					Summary:  "Expected type to be string",
					Detail:   "Type assertion failed, expected string type for Cloud Firewall NW Services Tags validation",
				},
			}
		}

		// Convert the cty.Path to a string representation
		pathStr := fmt.Sprintf("%+v", path)

		// Use StringInSlice from helper/validation package
		var diags diag.Diagnostics
		if _, errs := validation.StringInSlice(supportedCloudFirewallNwServicesTag, false)(value, pathStr); len(errs) > 0 {
			for _, err := range errs {
				diags = append(diags, diag.FromErr(err)...)
			}
		}

		return diags
	}
}
